version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '65432:65432'
    stdin_open: true
    tty: true
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
